import React, { useState } from 'react';
import { PayslipData } from '../types/payroll';
import { Mail, Copy, Check, X, Send, ShieldAlert } from 'lucide-react';

interface EmailShareModalProps {
  isOpen: boolean;
  onClose: () => void;
  payslip: PayslipData;
}

export const EmailShareModal: React.FC<EmailShareModalProps> = ({
  isOpen,
  onClose,
  payslip,
}) => {
  const [recipientEmail, setRecipientEmail] = useState(payslip.employee.email || '');
  const [copied, setCopied] = useState(false);
  const [sentSuccess, setSentSuccess] = useState(false);

  if (!isOpen) return null;

  const gross = payslip.earnings.reduce((s, e) => s + (Number(e.amount) || 0), 0);
  const deductions = payslip.deductions.reduce((s, d) => s + (Number(d.amount) || 0), 0);
  const net = gross - deductions;

  const summaryText = `
========================================
PAYSLIP STATEMENT: ${payslip.payPeriod.periodMonth.toUpperCase()}
========================================
Employer: ${payslip.company.name}
Employee: ${payslip.employee.fullName} (${payslip.employee.employeeCode})
Designation: ${payslip.employee.designation} - ${payslip.employee.department}
Payment Date: ${payslip.payPeriod.paymentDate}
Slip Reference: ${payslip.payPeriod.slipNumber}

EARNINGS BREAKDOWN:
${payslip.earnings.map((e) => `• ${e.name}: ${payslip.currency.symbol}${Number(e.amount).toLocaleString()}`).join('\n')}
----------------------------------------
Gross Earnings: ${payslip.currency.symbol}${gross.toLocaleString()}

DEDUCTIONS & TAXES:
${payslip.deductions.map((d) => `• ${d.name}: ${payslip.currency.symbol}${Number(d.amount).toLocaleString()}`).join('\n')}
----------------------------------------
Total Deductions: ${payslip.currency.symbol}${deductions.toLocaleString()}

========================================
NET PAYABLE SALARY: ${payslip.currency.symbol}${net.toLocaleString()}
========================================
Bank Account: ${payslip.employee.bankName} (${payslip.employee.bankAccount})
Confidential statement generated by ${payslip.company.name} Payroll System.
  `.trim();

  const handleCopy = () => {
    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleSendSimulation = (e: React.FormEvent) => {
    e.preventDefault();
    setSentSuccess(true);
    setTimeout(() => {
      setSentSuccess(false);
      onClose();
    }, 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/80 backdrop-blur-xs p-4">
      <div className="bg-white border border-slate-300 w-full max-w-lg rounded-sm shadow-2xl overflow-hidden animate-fadeIn">
        {/* Header */}
        <div className="bg-slate-900 text-white p-4 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <Mail className="w-4 h-4 text-slate-300" />
            <h3 className="text-sm font-black uppercase tracking-wider">
              Send / Share Payslip Statement
            </h3>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white p-1">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-4">
          <form onSubmit={handleSendSimulation} className="space-y-3">
            <div>
              <label className="block text-[11px] font-bold uppercase tracking-wider text-slate-600 mb-1">
                Employee Email Address
              </label>
              <input
                type="email"
                required
                value={recipientEmail}
                onChange={(e) => setRecipientEmail(e.target.value)}
                placeholder="employee@company.com"
                className="w-full px-3 py-2 text-xs border border-slate-300 rounded-xs focus:ring-1 focus:ring-slate-900"
              />
            </div>

            <div>
              <label className="block text-[11px] font-bold uppercase tracking-wider text-slate-600 mb-1">
                Payslip Summary Text
              </label>
              <textarea
                rows={6}
                readOnly
                value={summaryText}
                className="w-full p-2.5 text-[11px] font-mono border border-slate-200 bg-slate-50 rounded-xs text-slate-700 resize-none"
              />
            </div>

            <div className="flex items-center gap-2 pt-1">
              <button
                type="button"
                onClick={handleCopy}
                className="flex-1 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-bold uppercase tracking-wider rounded-xs border border-slate-300 flex items-center justify-center gap-1.5 transition-colors"
              >
                {copied ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-600" />
                    Copied to Clipboard!
                  </>
                ) : (
                  <>
                    <Copy className="w-3.5 h-3.5" />
                    Copy Plaintext Summary
                  </>
                )}
              </button>

              <button
                type="submit"
                className="flex-1 py-2 bg-slate-900 hover:bg-slate-800 text-white text-xs font-bold uppercase tracking-wider rounded-xs flex items-center justify-center gap-1.5 transition-colors"
              >
                {sentSuccess ? (
                  <>
                    <Check className="w-3.5 h-3.5 text-emerald-400" />
                    Statement Dispatched!
                  </>
                ) : (
                  <>
                    <Send className="w-3.5 h-3.5" />
                    Send Digital Payslip
                  </>
                )}
              </button>
            </div>
          </form>

          <div className="flex items-start gap-2 bg-slate-50 p-2.5 rounded-xs border border-slate-200 text-[10px] text-slate-500">
            <ShieldAlert className="w-4 h-4 text-slate-400 shrink-0 mt-0.5" />
            <p>
              Salary details are encrypted and formatted for formal HR compliance and employee records.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
