import { Currency, PayslipData } from '../types/payroll';

export const CURRENCIES: Currency[] = [
  { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-US' },
  { code: 'EUR', symbol: '€', name: 'Euro', locale: 'de-DE' },
  { code: 'GBP', symbol: '£', name: 'British Pound', locale: 'en-GB' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee', locale: 'en-IN' },
  { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', locale: 'en-CA' },
  { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', locale: 'en-AU' },
  { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', locale: 'en-SG' },
  { code: 'AED', symbol: 'AED', name: 'UAE Dirham', locale: 'en-AE' },
  { code: 'SAR', symbol: 'SAR', name: 'Saudi Riyal', locale: 'en-SA' },
  { code: 'JPY', symbol: '¥', name: 'Japanese Yen', locale: 'ja-JP' },
  { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', locale: 'de-CH' },
];

export const INITIAL_PAYSLIP_DATA: PayslipData = {
  id: 'PAY-2023-10922',
  currency: CURRENCIES[0],
  company: {
    name: 'NEXUS CORP SOLUTIONS',
    tagline: 'Enterprise Cloud & Design Systems',
    address: '122 Innovation Drive, Suite 400',
    cityStateZip: 'Tech City, CA 94016',
    country: 'United States',
    taxId: 'US-EIN-94-829104',
    regNumber: 'CORP-CA-2018-8831',
    email: 'payroll@nexuscorpsolutions.com',
    phone: '+1 (415) 890-2340',
    website: 'www.nexuscorpsolutions.com',
    signatoryName: 'Marcus Vance',
    signatoryTitle: 'Chief Financial Officer',
    stampText: 'VERIFIED & APPROVED FOR DISBURSEMENT',
  },
  employee: {
    id: 'emp-1',
    employeeCode: 'EMP-10922',
    fullName: 'Alexander J. Sterling',
    email: 'a.sterling@nexuscorp.io',
    phone: '+1 (415) 555-0198',
    designation: 'Senior UX Lead',
    department: 'Product Design',
    joiningDate: '2021-03-15',
    location: 'San Francisco HQ',
    bankName: 'Federal Reserve Bank',
    bankAccount: '•••• •••• •••• 4902',
    routingOrIfsc: '021000021',
    taxIdNumber: 'BVP-928-11',
    providentFundNo: 'PF-US-99281',
    daysInMonth: 30,
    daysWorked: 22,
    paidLeaves: 2,
    unpaidLeaves: 0,
    overtimeHours: 0,
    overtimeRatePerHour: 0,
  },
  payPeriod: {
    periodMonth: 'October 2023',
    periodLabel: 'Statement for October 2023',
    startDate: '2023-10-01',
    endDate: '2023-10-31',
    paymentDate: '2023-11-01',
    paymentMethod: 'Bank Transfer',
    referenceNo: 'NX-0092-2310',
    slipNumber: 'SLIP-2023-10-049',
  },
  earnings: [
    { id: 'e-1', name: 'Basic Salary', amount: 8500, isTaxable: true, type: 'fixed' },
    { id: 'e-2', name: 'House Rent Allowance (HRA)', amount: 2400, isTaxable: true, type: 'fixed' },
    { id: 'e-3', name: 'Conveyance Allowance', amount: 500, isTaxable: false, type: 'fixed' },
    { id: 'e-4', name: 'Special Incentives', amount: 1200, isTaxable: true, type: 'fixed' },
    { id: 'e-5', name: 'Quarterly Performance Bonus', amount: 2000, isTaxable: true, isBonus: true, type: 'fixed' },
  ],
  deductions: [
    { id: 'd-1', name: 'Provident Fund (PF) / 401(k)', amount: 1020, isStatutory: true, type: 'fixed' },
    { id: 'd-2', name: 'Income Tax (TDS / PAYE)', amount: 1850, isStatutory: true, type: 'fixed' },
    { id: 'd-3', name: 'Professional Tax', amount: 200, isStatutory: true, type: 'fixed' },
    { id: 'd-4', name: 'Health Insurance Premium', amount: 450, isStatutory: false, type: 'fixed' },
  ],
  employerContributions: [
    { id: 'ec-1', name: 'Employer 401(k) Match (12%)', amount: 1020 },
    { id: 'ec-2', name: 'Company Medical & Dental Contribution', amount: 650 },
    { id: 'ec-3', name: 'Gratuity Fund Allocation', amount: 408 },
  ],
  showEmployerContributions: false,
  ytd: {
    enabled: true,
    ytdGross: 146000,
    ytdTax: 18500,
    ytdDeductions: 35200,
    ytdNet: 110800,
  },
  notes: 'Salaries are strictly confidential. All statutory taxes have been computed in compliance with federal guidelines.',
  confidentialityNotice: 'This document contains confidential information. Unauthorized distribution or reproduction is prohibited.',
  templateStyle: 'geometric',
};

export const SAMPLE_EMPLOYEES = [
  {
    id: 'emp-1',
    employeeCode: 'EMP-10922',
    fullName: 'Alexander J. Sterling',
    email: 'a.sterling@nexuscorp.io',
    phone: '+1 (415) 555-0198',
    designation: 'Senior UX Lead',
    department: 'Product Design',
    joiningDate: '2021-03-15',
    location: 'San Francisco HQ',
    bankName: 'Federal Reserve Bank',
    bankAccount: '•••• •••• •••• 4902',
    routingOrIfsc: '021000021',
    taxIdNumber: 'BVP-928-11',
    providentFundNo: 'PF-US-99281',
    daysInMonth: 30,
    daysWorked: 22,
    paidLeaves: 2,
    unpaidLeaves: 0,
    overtimeHours: 0,
    overtimeRatePerHour: 0,
    earnings: [
      { id: 'e-1', name: 'Basic Salary', amount: 8500, isTaxable: true },
      { id: 'e-2', name: 'House Rent Allowance (HRA)', amount: 2400, isTaxable: true },
      { id: 'e-3', name: 'Conveyance Allowance', amount: 500, isTaxable: false },
      { id: 'e-4', name: 'Special Incentives', amount: 1200, isTaxable: true },
      { id: 'e-5', name: 'Quarterly Performance Bonus', amount: 2000, isTaxable: true, isBonus: true },
    ],
    deductions: [
      { id: 'd-1', name: 'Provident Fund (PF)', amount: 1020, isStatutory: true },
      { id: 'd-2', name: 'Income Tax (TDS)', amount: 1850, isStatutory: true },
      { id: 'd-3', name: 'Professional Tax', amount: 200, isStatutory: true },
      { id: 'd-4', name: 'Health Insurance', amount: 450, isStatutory: false },
    ],
  },
  {
    id: 'emp-2',
    employeeCode: 'EMP-10923',
    fullName: 'Elena Rostova',
    email: 'e.rostova@nexuscorp.io',
    phone: '+1 (415) 555-0812',
    designation: 'Principal Staff Engineer',
    department: 'Core Infrastructure',
    joiningDate: '2019-06-01',
    location: 'Austin Campus',
    bankName: 'JPMorgan Chase Bank',
    bankAccount: '•••• •••• •••• 8104',
    routingOrIfsc: '111000038',
    taxIdNumber: 'TX-901-44',
    providentFundNo: 'PF-US-88123',
    daysInMonth: 30,
    daysWorked: 22,
    paidLeaves: 1,
    unpaidLeaves: 0,
    overtimeHours: 5,
    overtimeRatePerHour: 75,
    earnings: [
      { id: 'e-1', name: 'Basic Salary', amount: 11500, isTaxable: true },
      { id: 'e-2', name: 'House Rent Allowance (HRA)', amount: 3200, isTaxable: true },
      { id: 'e-3', name: 'Conveyance Allowance', amount: 600, isTaxable: false },
      { id: 'e-4', name: 'Tech & Research Stipend', amount: 1500, isTaxable: true },
      { id: 'e-5', name: 'Overtime Pay (5 hrs)', amount: 375, isTaxable: true },
    ],
    deductions: [
      { id: 'd-1', name: 'Provident Fund (PF) / 401(k)', amount: 1380, isStatutory: true },
      { id: 'd-2', name: 'Income Tax (TDS)', amount: 2750, isStatutory: true },
      { id: 'd-3', name: 'Professional Tax', amount: 200, isStatutory: true },
      { id: 'd-4', name: 'Comprehensive Health Cover', amount: 520, isStatutory: false },
    ],
  },
  {
    id: 'emp-3',
    employeeCode: 'EMP-10924',
    fullName: 'David Chen',
    email: 'd.chen@nexuscorp.io',
    phone: '+1 (415) 555-0349',
    designation: 'Growth Marketing Director',
    department: 'Marketing & Sales',
    joiningDate: '2022-01-10',
    location: 'New York Hub',
    bankName: 'Citibank N.A.',
    bankAccount: '•••• •••• •••• 6231',
    routingOrIfsc: '021000089',
    taxIdNumber: 'NY-332-90',
    providentFundNo: 'PF-US-77412',
    daysInMonth: 30,
    daysWorked: 21,
    paidLeaves: 2,
    unpaidLeaves: 1,
    overtimeHours: 0,
    overtimeRatePerHour: 0,
    earnings: [
      { id: 'e-1', name: 'Basic Salary', amount: 9200, isTaxable: true },
      { id: 'e-2', name: 'House Rent Allowance (HRA)', amount: 2800, isTaxable: true },
      { id: 'e-3', name: 'Sales Pipeline Commission', amount: 3500, isTaxable: true, isBonus: true },
      { id: 'e-4', name: 'Client Entertainment Allowance', amount: 800, isTaxable: false },
    ],
    deductions: [
      { id: 'd-1', name: 'Provident Fund (PF) / 401(k)', amount: 1104, isStatutory: true },
      { id: 'd-2', name: 'Income Tax (TDS)', amount: 2400, isStatutory: true },
      { id: 'd-3', name: 'Loss of Pay (1 day unpaid)', amount: 306, isStatutory: false },
      { id: 'd-4', name: 'Health & Dental Plan', amount: 480, isStatutory: false },
    ],
  },
  {
    id: 'emp-4',
    employeeCode: 'EMP-10925',
    fullName: 'Sophia Martinez',
    email: 's.martinez@nexuscorp.io',
    phone: '+1 (415) 555-0921',
    designation: 'People Operations Specialist',
    department: 'Human Resources',
    joiningDate: '2022-08-15',
    location: 'San Francisco HQ',
    bankName: 'Wells Fargo Bank',
    bankAccount: '•••• •••• •••• 1159',
    routingOrIfsc: '121000247',
    taxIdNumber: 'CA-883-12',
    providentFundNo: 'PF-US-66290',
    daysInMonth: 30,
    daysWorked: 22,
    paidLeaves: 0,
    unpaidLeaves: 0,
    overtimeHours: 0,
    overtimeRatePerHour: 0,
    earnings: [
      { id: 'e-1', name: 'Basic Salary', amount: 6200, isTaxable: true },
      { id: 'e-2', name: 'House Rent Allowance (HRA)', amount: 1800, isTaxable: true },
      { id: 'e-3', name: 'Conveyance Allowance', amount: 450, isTaxable: false },
      { id: 'e-4', name: 'HR Operations Stipend', amount: 600, isTaxable: true },
    ],
    deductions: [
      { id: 'd-1', name: 'Provident Fund (PF) / 401(k)', amount: 744, isStatutory: true },
      { id: 'd-2', name: 'Income Tax (TDS)', amount: 1120, isStatutory: true },
      { id: 'd-3', name: 'Professional Tax', amount: 200, isStatutory: true },
      { id: 'd-4', name: 'Medical Insurance', amount: 380, isStatutory: false },
    ],
  },
];
